version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    stdin_open: true
    tty: true
